### ISSUE TITLE
TAVILY_API_KEY environment variable is required in docker-compose.yml

### ISSUE THREAD

**Issue by ParkJaeSeong** [assafelovic/gpt-researcher#246]
Thank you for creating a great program. Thank you for greatly shortening Google search time.

Environment variable settings related to the recently changed tavily search api are missing from docker-compose.yml.

I handled it as below: Please refer to it and reflect on it.

```
diff --git a/docker-compose.yml b/docker-compose.yml
index 05c9ec1..46906ec 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -5,5 +5,6 @@ services:
     build: ./
     environment:
       OPENAI_API_KEY: ${OPENAI_API_KEY}
+      TAVILY_API_KEY: ${TAVILY_API_KEY}
     ports:
-      - 8000:8000
\ No newline at end of file
+      - 8000:8000
```

**Comment by Ethan-Otto** [comment]
I was just about to post about this, great job

**Comment by assafelovic** [comment]
Great catch @ParkJaeSeong thank you. Fixed in this commit: https://github.com/assafelovic/gpt-researcher/commit/f3654df84e22a9bcb840f8b30e3eda09da18447b

**Comment by assafelovic** [comment]
@Ethan-Otto looks like requests are not forwarded to you docker. @ParkJaeSeong can you confirm if this happens to you as well?

**Comment by ParkJaeSeong** [comment]
I had a problem after the update, but it wasn't @Ethan-Otto's problem.
After initializing the docker cache by running the command below, I had no problems.

`docker builder prune`

**Comment by Ethan-Otto** [comment]
Odd still doesn't work for me
![image](https://github.com/assafelovic/gpt-researcher/assets/89815515/201494e8-0e7a-49ee-b3ad-4784bc6ce0e4)
![image](https://github.com/assafelovic/gpt-researcher/assets/89815515/b72dfe2a-9b6a-43e4-8852-5ff0fbeb4b8a)

**Comment by ParkJaeSeong** [comment]
@Ethan-Otto , These are my configuration files.

```
❯ cat docker-compose.yml
version: '3'
services:
  gpt-researcher:
    image: assafelovic/gpt-researcher
    build: ./
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    ports:
      - 8000:8000
```   

```
❯ cat Dockerfile
FROM python:3.11.4-slim-bullseye as install-browser

RUN apt-get update \
    && apt-get satisfy -y \
    "chromium, chromium-driver (>= 115.0)" \
    && chromium --version && chromedriver --version

RUN apt-get install -y firefox-esr wget \
    && wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz \
    && tar -xvzf geckodriver* \
    && chmod +x geckodriver \
    && mv geckodriver /usr/local/bin/

FROM install-browser as gpt-researcher-install

ENV PIP_ROOT_USER_ACTION=ignore

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

FROM gpt-researcher-install AS gpt-researcher

RUN useradd -ms /bin/bash gpt-researcher \
    && chown -R gpt-researcher:gpt-researcher /usr/src/app

USER gpt-researcher

COPY --chown=gpt-researcher:gpt-researcher ./ ./

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
```

The last line seems to have a different `127.0.0.1` → `0.0.0.0`.
I hope this resolves the issue.

**Comment by Ethan-Otto** [comment]
@ParkJaeSeong Ah, I didn't realize that I need to connect to localhost not 0.0.0.0. It seems to work now.  Thanks!

**Comment by ParkJaeSeong** [comment]
Great. Now I can close this issue. Thanks
